export const COMMON_PLANTS = [
  { id: 'pothos', name: 'Pothos', difficulty: 'easy' },
  { id: 'snake-plant', name: 'Snake Plant', difficulty: 'easy' },
  { id: 'spider-plant', name: 'Spider Plant', difficulty: 'easy' },
  { id: 'peace-lily', name: 'Peace Lily', difficulty: 'easy' },
  { id: 'monstera', name: 'Monstera', difficulty: 'moderate' },
  { id: 'fiddle-leaf-fig', name: 'Fiddle Leaf Fig', difficulty: 'hard' },
  { id: 'rubber-plant', name: 'Rubber Plant', difficulty: 'moderate' },
  { id: 'zz-plant', name: 'ZZ Plant', difficulty: 'easy' },
  { id: 'philodendron', name: 'Philodendron', difficulty: 'easy' },
  { id: 'calathea', name: 'Calathea', difficulty: 'hard' },
  { id: 'fern', name: 'Fern', difficulty: 'moderate' },
  { id: 'succulent', name: 'Succulent', difficulty: 'easy' },
  { id: 'cactus', name: 'Cactus', difficulty: 'easy' },
  { id: 'orchid', name: 'Orchid', difficulty: 'hard' },
  { id: 'aloe-vera', name: 'Aloe Vera', difficulty: 'easy' },
];
